image: python:latest

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - apt-get update
    - apt-get install -y gfortan
    - pip3 install .

staging:
  stage: deploy
  script:
    - echo "Staging"
  only:
    - master

production:
  stage: deploy
  script:
    - echo "Production"
  only:
    - tags